/lslidar_driver_node:
  ros__parameters: 
    frame_id: lidar_link                                    # 清扫机器人激光雷达坐标系
    group_ip: 224.1.1.2
    add_multicast: false 
    device_ip: 192.168.1.200                               # 雷达源IP
    device_ip_difop: 192.168.1.102                         # 雷达目的ip
    msop_port: 2368                                        # 雷达目的端口号
    difop_port: 2369                                       # 雷达源端口号
    lidar_name: N10_P                                      # 雷达型号：N10P
    angle_disable_min: -1.0                                # 不裁剪角度，使用全范围扫描
    angle_disable_max: -1.0                                # 不裁剪角度，使用全范围扫描
    min_range: 0.1                                         # 雷达接收距离最小值（米）
    max_range: 20.0                                        # 雷达接收距离最大值（米），适合室内清扫
    use_gps_ts: false                                      # 不使用GPS授时
    scan_topic: /cleaning_robot/scan                       # 清扫机器人激光数据话题
    interface_selection: serial                            # 使用串口连接
    serial_port_: /dev/ttyUSB1                            # 串口设备号（可能需要根据实际情况调整）
    high_reflection: false                                 # N10P雷达配置
    compensation: false                                    # 不使用角度补偿
    pubScan: true                                         # 发布scan话题
    pubPointCloud2: true                                  # 同时发布点云话题
    pointcloud_topic: /cleaning_robot/pointcloud          # 清扫机器人点云话题 