/lslidar_driver_node:
  ros__parameters: 
    frame_id: lidar_link                                    #激光坐标系
    group_ip: 224.1.1.2                                    #组播IP地址
    add_multicast: false                                    #是否启用组播
    device_ip: 192.168.1.200                               #雷达IP地址
    device_ip_difop: 192.168.1.102                         #本机IP地址  
    msop_port: 2368                                        #数据端口号
    difop_port: 2369                                       #控制端口号
    lidar_name: N10_P                                      #雷达型号：N10_P
    angle_disable_min: 0.0                                 #角度裁剪开始值（360°扫描）
    angle_disable_max: 0.0                                 #角度裁剪结束值（360°扫描）
    min_range: 0.1                                         #最小测距距离 (m)
    max_range: 20.0                                        #最大测距距离 (m)
    use_gps_ts: false                                      #不使用GPS授时
    scan_topic: /cleaning_robot/scan                       #激光扫描话题名称
    interface_selection: net                               #接口选择：网络通讯
    serial_port_: /dev/ttyUSB1                            #串口号（网络模式下无效）
    high_reflection: false                                 #N10P高反射功能
    compensation: false                                    #角度补偿功能
    pubScan: true                                         #发布scan话题
    pubPointCloud2: true                                  #发布点云话题
    pointcloud_topic: /cleaning_robot/pointcloud          #点云话题名称 